### ISSUE TITLE
Not included in Quicklisp

### ISSUE THREAD

**Issue by pnathan** [lisp/de.setf.amqp#1]
Hi,

I am interested in using your library with RabbitMQ and SBCL 1.0.57; however, it isn't in Quicklisp. It would be really nice if it was in Quicklisp.

If there's anything I can do to help you out there, let me know.

regards,
Paul

**Comment by rigidus** [comment]
I join this issue

**Comment by lisp** [comment]
as my primary use is in production, the path through quick lisp adds no benefit and, as such, there has been no motivation to go through the process with this and the libraries on which it depends.

please, feel free to do whatever is necessary to include it and let me know.

**Comment by rigidus** [comment]
I tried to do it, but ran into problems when connecting libraries com.b9.puri.ppcre. It parses the connection string is incorrect. I ask you actual for for this project version of the library, if it is available

**Comment by lisp** [comment]
On 16 Apr 2014, at 12:52, Rigidus notifications@github.com wrote:

> I tried to do it, but ran into problems when connecting libraries com.b9.puri.ppcre. It parses the connection string is incorrect.

i do not understand, what you mean with “connection string”, do you mean the system name?

> I ask you actual for for this project version of the library, if it is available
> 
> the code which i build with constantly is in the respective project in this account.
> i last pulled it sometime this morning.
> —
> Reply to this email directly or view it on GitHub.

---

james anderson | james@dydra.com | http://dydra.com

**Comment by rigidus** [comment]
I pulled:
amqp-1-1-0-8-0
amqp-1-1-0-9-0
amqp-1-1-0-9-1
com.b9.puri.ppcre
de.setf.amqp
de.setf.codecs
de.setf.mime
de.setf.utility
..and made a few changes for built with quicklisp

When I try eval (defparameter _c_ (make-instance 'amqp:connection :uri "amqp://guest:guest@localhost/"))

error occurs: port is not a number: GUEST@LOCALHOST.
in com.b9.puri:parse-uri

I tried to change the code inside com.b9.puri and it seemed to me that de.setf.amqp wants to have another version of the library

**Comment by lisp** [comment]
i do not yet follow what is different in your build. i build with immediate pulls from the repository

```
/development/source/library/com/b9/puri$ git remote show origin
* remote origin
  Fetch URL: git@github.com:lisp/com.b9.puri.ppcre.git
  Push  URL: git@github.com:lisp/com.b9.puri.ppcre.git
  HEAD branch: master
/development/source/library/com/b9/puri$ git status
# On branch master
nothing to commit (working directory clean)
```

with a the result which performs as follows:

```
> (inspect (puri:uri "amqp://guest:guest@localhost/"))
 #<ORG.DATAGRAPH.SPOCQ.IMPLEMENTATION::REPOSITORY-METADATA {10210AC111}>) 
The object is a STANDARD-OBJECT of type PURI:URI.
0. SCHEME: :AMQP
1. HOST: "localhost"
2. PORT: NIL
3. PATH: "/"
4. QUERY: NIL
5. FRAGMENT: NIL
6. PLIST: (PURI::USERINFO "guest:guest")
7. ESCAPED: NIL
8. STRING: "amqp://guest:guest@localhost/"
9. PARSED-PATH: NIL
10. HASHCODE: NIL
```

which i understand to be correct. in production, with this code, we use uri with similar form - just without the trailing "/".

**Comment by rigidus** [comment]
I'm sorry, the problems were caused by my crooked hands :) Now I was able to run all the systems  through quicklisp. 

Now I have difficulty with the system rabbito. Some features I find in other packages. Relevant whether this system?

**Comment by rigidus** [comment]
/s/rabbito/rabbitmq

**Comment by lisp** [comment]
good evening;

**Comment by rigidus** [comment]
Good day :) Thank you! And if not a secret what is used in production?

**Comment by lisp** [comment]
good afternoon,

On 16 Apr 2014, at 17:06, Rigidus notifications@github.com wrote:

> Good day :) Thank you! And if not a secret what is used in production?

http://www.dydra.com has been running this code with a rabbitmq broker for several years.
with rmq at version : {rabbit,"RabbitMQ","2.8.4”}, i believe, it uses the 1-1-0-9-1 version protocol.

best regards, from berlin,

**Comment by rigidus** [comment]
Eh, I'd give to see this code :) At least send / receive messages :)
Best regards, from Saint-Petersburg, Russia

**Comment by lisp** [comment]
On 16 Apr 2014, at 17:19, Rigidus notifications@github.com wrote:

> Eh, I'd give to see this code :) At least send / receive messages :)

i am not sure what you mean?
the broker side is exactly the github code and the server side is nothing more than the streaming examples, just lots of them simultaneously with somewhat more error handling.
?

**Comment by rigidus** [comment]
I just want to create a working example, and that its inclusion in quicklisp that the community could use this library

**Comment by lisp** [comment]
good afternoon,

**Comment by rigidus** [comment]
I try eval this example: 

(defparameter _d_ (make-instance 'amqp:connection :uri "amqp://guest:guest@localhost/"))
(amqp:with-open-channel (output _d_  :exchange "ex" :type "direct" :queue "q3")
   (format output "~a, ~a, ~a~%"
               (lisp-implementation-type) 
               (lisp-implementation-version) 
               amqp.u:_version_))

... and get an error:

end of file on #<AMQP-1-1-0-9-1:CHANNEL  [#<PURI:URI amqp://localhost/>].1 {10073EFAF3}>
   [Condition of type END-OF-FILE]

Backtrace: https://gist.github.com/rigidus/10970256

However, I see that the queue is created, although it 0 messages.

Maybe I made a mistake when passing parameters?

**Comment by rigidus** [comment]
Good morning!
James, I was not able to solve the problem. But I probably could get the
boss to pay for your work. On what amount can we talk?

2014-04-16 19:44 GMT+04:00 james anderson notifications@github.com:

> good afternoon,
>

**Comment by lisp** [comment]
as noted 16.4, the problem is not with this system.
